# Generated by Django 4.2.3 on 2023-07-31 20:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartAndCheckoutInfo',
            fields=[
                ('cart_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('cart_token', models.CharField(max_length=32)),
                ('cart_created', models.BooleanField(default=False)),
                ('cart_creation_time', models.TimeField(default=datetime.datetime(2023, 8, 1, 1, 31, 8, 136624))),
                ('cart_updation_time', models.TimeField(null=True)),
                ('order_created', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutReminderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('first_reminder_sent', models.BooleanField(default=False, null=True)),
                ('t2', models.DurationField(default=datetime.timedelta(days=1))),
                ('second_reminder_sent', models.BooleanField(default=False, null=True)),
                ('t3', models.DurationField(default=datetime.timedelta(days=3))),
                ('third_reminder_sent', models.BooleanField(default=False, null=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhooks.cartandcheckoutinfo')),
            ],
        ),
    ]
