# Generated by Django 4.2.3 on 2023-07-31 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartandcheckoutinfo',
            name='cart_creation_time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 1, 3, 7, 31, 549512)),
        ),
    ]
