# Generated by Django 4.2.3 on 2023-07-31 22:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_alter_cartandcheckoutinfo_cart_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartandcheckoutinfo',
            name='cart_creation_time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 1, 3, 54, 32, 901385)),
        ),
        migrations.AlterField(
            model_name='checkoutreminderinfo',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='webhooks.cartandcheckoutinfo'),
        ),
    ]
