# Generated by Django 4.2.3 on 2023-08-01 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_alter_cartandcheckoutinfo_cart_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartandcheckoutinfo',
            name='cart_creation_time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 1, 13, 39, 20, 882632)),
        ),
    ]
